# Generated by Django 2.1.3 on 2018-11-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('participants', models.ManyToManyField(to='takeda_app.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='takeda_app.Department')),
                ('executors', models.ManyToManyField(to='takeda_app.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('deadline', models.DateTimeField(default='2019-01-01 00:00:00')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='takeda_app.Department')),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='takeda_app.Worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_title',
        ),
        migrations.AddField(
            model_name='mark',
            name='mark',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_tasks',
            field=models.ManyToManyField(to='takeda_app.Task'),
        ),
        migrations.AddField(
            model_name='mark',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='takeda_app.Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='tasks_created',
            field=models.ManyToManyField(to='takeda_app.Task'),
        ),
    ]
