# Generated by Django 2.1.3 on 2018-11-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0002_auto_20181123_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='deparmnent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='takeda_app.Department'),
            preserve_default=False,
        ),
    ]
