# Generated by Django 2.1.3 on 2018-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0004_auto_20181125_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(to='takeda_app.Worker'),
        ),
    ]
