# Generated by Django 2.1.3 on 2018-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0005_auto_20181125_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2019-01-01 00:00:00'),
        ),
    ]
