# Generated by Django 2.1.3 on 2018-11-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0006_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark',
            new_name='mark_num',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='marks',
        ),
        migrations.AddField(
            model_name='mark',
            name='workers',
            field=models.ManyToManyField(to='takeda_app.Mark'),
        ),
    ]
