# Generated by Django 2.1.3 on 2018-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeda_app', '0008_auto_20181126_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(default='test@mail.ru', max_length=60),
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='111', max_length=60),
        ),
    ]
